var sets = { set_one: [
    ['가구', 'gagu_H.mp3', 'gagu_M.mp3', 'furniture'],
    ['가나다', 'ganada_H.mp3', 'ganada_M.mp3', 'korean alphabet'],
    ['가다', 'gada_H.mp3', 'gada_M.mp3', 'to go'],
    ['가두다', 'gaduda_H.mp3', 'gaduda_M.mp3', 'to lock in'],
    ['고구마', 'goguma_H.mp3', 'goguma_M.mp3', 'sweet potato'],
    ['고기', 'gogi_H.mp3', 'gogi_M.mp3', 'meat'],
    ['고모', 'gomo_H.mp3', 'gomo_M.mp3', 'father\'s sister'],
    ['구두', 'gudu_H.mp3', 'gudu_M.mp3', 'dress shoes'],
    ['기도', 'gido_H.mp3', 'gido_M.mp3', 'prayer'],
    ['나가다', 'nagada_H.mp3', 'nagada_M.mp3', 'go out'],
    ['나누다', 'nanuda_H.mp3', 'nanuda_M.mp3', 'to divide'],
    ['나무', 'namu_H.mp3', 'namu_M_(1).mp3', 'tree'],
    ['나오다', 'naoda_H.mp3', 'naoda_M.mp3', 'to come out'],
    ['나이', 'nai_H.mp3', 'nai_M.mp3', 'age'],
    ['누가', 'nuga_H.mp3', 'nuga_M.mp3', 'who'],
    ['두구', 'nugu_H.mp3', 'nugu_M.mp3', 'who'],
    ['누나', 'nuna_H.mp3', 'nuna_M.mp3', 'older sister'],
    ['다가가다', 'dagagada_H.mp3', 'dagagada_M.mp3', 'approach to someone'],
    ['다니다', 'danida_H.mp3', 'danida_M.mp3', 'to go to'],
    ['도구', 'dogu_H.mp3', 'dogu_M.mp3', 'instrument, tool'],
    ['마다', 'mada_H.mp3', 'mada_M.mp3', 'every'],
    ['마디', 'madi_H.mp3', 'madi_M.mp3', 'joint, knot'],
    ['모기', 'mogi_H.mp3', 'mogi_M.mp3', 'mosquito'],
    ['아기', 'agi_H.mp3', 'agi_M.mp3', 'baby'],
    ['아마도', 'amado_H.mp3', 'amado_M.mp3', 'maybe'],
    ['아우', 'au_H.mp3', 'au_M.mp3', 'man\'s younger brother (archaic)'],
    ['아이', 'ai_H.mp3', 'ai_M.mp3', 'child'],
    ['오다', 'oda_H.mp3', 'oda_M.mp3', 'to come'],
    ['오이', 'oi_H_(1).mp3', 'oi_M.mp3', 'cucumber'],
    ['이기다', 'igida_H.mp3', 'igida_M.mp3', 'to win'],
    ['이모', 'imo_H.mp3', 'imo_M.mp3', 'mother\'s sister']
  ],
  set_two: [
    ['가게','gage_H.mp3','gage_M.mp3','store'],
    ['가로','garo_H.mp3','garo_M_.mp3','the width'],
    ['가로수','garosu_H.mp3','garosu_M.mp3','trees lining a street'],
    ['가르마','gareuma_H.mp3','gareuma_M.mp3','a part in one\'s hair'],
    ['가사','gasa_H.mp3','gasa_M.mp3','the words of a song'],
    ['가수','gasu_H.mp3','gasu_M.mp3','singer'],
    ['가스','gaseu_H.mp3','gaseu_M.mp3','gas'],
    ['가루','garu_H.mp3','garu_M.mp3','powder'],
    ['개','gae_H.mp3','gae_M.mp3','dog'],
    ['개미','gaemi_H.mp3','gaemi_M.mp3','ant'],
    ['거기','geogi_H.mp3','geogi_M.mp3','there'],
    ['거리','geori_H.mp3','geori_M.mp3','street, distance'],
    ['게','ge_H.mp3','ge_M.mp3','crab'],
    ['기내','gine_H.mp3','gine_M.mp3','the inside of a plane'],
    ['기다리다','gidarida_H.mp3','gidarida_M.mp3','to wait'],
    ['고래','gorae_H.mp3','gorae_M.mp3','whale'],
    ['구조','gujo_H.mp3','gujo_M.mp3','rescue'],
    ['나라','nara_H.mp3','nara_M.mp3','country'],
    ['나르다','nareuda_H.mp3','nareuda_M.mp3','to carry'],
    ['나이','nai_H.mp3','nai_M.mp3','age'],
    ['나사','nasa_H.mp3','nasa_M.mp3','screw'],
    ['나비','nabi_H.mp3','nabi_M.mp3','butterfly'],
    ['내리다','naerida_H.mp3','naerida_M.mp3','to go descend'],
    ['네','ne_H.mp3','ne_M.mp3','yes'],
    ['내','nae_H.mp3','nae_M.mp3','my'],
    ['네모','nemo_H.mp3','nemo_M.mp3','square'],
    ['너구리','neoguri_H.mp3','neoguri_M.mp3','raccoon'],
    ['노루','noru_H.mp3','noru_M.mp3','roe deer'],
    ['노래','norae_H.mp3','norae_M.mp3','song'],
    ['다리','dari_H.mp3','dari_M.mp3','leg, bridge'],
    ['다시','dasi_H.mp3','dasi_M.mp3','again'],
    ['대구','daegu_H.mp3','daegu_M.mp3','Daegu, the name of a Korean city'],
    ['데우다','deuda_H.mp3','deuda_M.mp3','to reheat, to heat up'],
    ['도마','doma_H.mp3','doma_M.mp3','chopping board'],
    ['도시','dosi_H.mp3','dosi_M.mp3','city'],
    ['두부','dubu_H.mp3','dubu_M.mp3','soybean curd, tobu'],
    ['드디어','deudieo_H.mp3','deudieo_M.mp3','finally'],
    ['드라마','Drama_H.mp3','Drama_M.mp3','drama'],
    ['라디오','radio_H.mp3','radio_M.mp3','radio'],
    ['로시아','reosia_H.mp3','reosia_M.mp3','Russia'],
    ['마루','maru_H.mp3','maru_M.mp3','wooden floor'],
    ['마리','mari_H.mp3','mari_M.mp3','counter for animals'],
    ['마르다','mareuda_H.mp3','mareuda_M.mp3','to get dry'],
    ['마시다','masida_H.mp3','masida_M.mp3','to drink'],
    ['머무르다','meomuruda_H.mp3','meomuruda_M.mp3','to stay'],
    ['매다','maeda_H.mp3','maeda_M.mp3','to tie'],
    ['매미','maemi_H.mp3','maemi_M.mp3','cicada'],
    ['매우','maeu_H.mp3','maeu_M.mp3','very'],
    ['머리','meori_H.mp3','meori_M.mp3','head'],
    ['메다','meda_H.mp3','meda_M.mp3','to shoulder'],
    ['메모','memo_H.mp3','memo_M.mp3','memo'],
    ['모두','modu_H.mp3','modu_M.mp3','every'],
    ['모래','more_H.mp3','more_M.mp3','sand'],
    ['모르다','moreuda_H.mp3','moreuda_M.mp3','to not know'],
    ['모자','moja_H.mp3','moja_M.mp3','cap, hat'],
    ['무게','muge_H.mp3','muge_M.mp3','weight'],
    ['무대','mudae_H.mp3','mudae_M.mp3','a stage'],
    ['미래','mirae_H.mp3','mirae_M.mp3','future'],
    ['미로','miro_H.mp3','miro_M.mp3','labyrinth'],
    ['미소','miso_H.mp3','miso_M.mp3','smile'],
    ['바가지','bagaji_H.mp3','bagaji_M.mp3','a rip off'],
    ['바보','babo_H.mp3','babo_M.mp3','fool, idiot'],
    ['바지','baji_H.mp3','baji_M.mp3','pants'],
    ['배','bae_H.mp3','bae_M.mp3','pear, ship, abdomen'],
    ['배우','baeu_H.mp3','baeu_M.mp3','actor/actress'],
    ['배우다','baeuda_H.mp3','baeuda_M.mp3','to learn'],
    ['버리다','beorida_H.mp3','beorida_M.mp3','to throw away'],
    ['버스','beoseu_H.mp3','beoseu_M.mp3','bus'],
    ['베개','bege_H.mp3','bege_M.mp3','pillow'],
    ['베다','beda_H.mp3','beda_M.mp3','to lay one´s head on, to cut'],
    ['보내다','bonaeda_H.mp3','bonaeda_M.mp3','to send'],
    ['보다','boda_H.mp3','boda_M.mp3','to see, to look, to watch'],
    ['보라','bora_H.mp3','bora_M.mp3','purple'],
    ['보리','bori_H.mp3','bori_M.mp3','barley'],
    ['부모','bumo_H.mp3','bumo_M_.mp3','parents'],
    ['부자','buja_H.mp3','buja_M.mp3','rich person'],
    ['비','bi_H.mp3','bi_M.mp3','rain'],
    ['비자','bija_H.mp3','bija_M.mp3','visa'],
    ['사고','sago_H.mp3','sago_M.mp3','accident'],
    ['서다','seoda_H.mp3','seoda_M.mp3','to stand, to stop'],
    ['서비스','Service_H.mp3','Service_M.mp3','service'],
    ['새다','saeda_H.mp3','saeda_M.mp3','to leak out, to dawn'],
    ['새우','saeu_H.mp3','saeu_M.mp3','shrimp'],
    ['세다','seda_H.mp3','seda_M.mp3','to count, to strong'],
    ['세로','sero_H.mp3','sero_M.mp3','length height'],
    ['세모','semo_H.mp3','semo_M.mp3','triangular'],
    ['세수','sesu_H.mp3','sesu_M.mp3','face washing'],
    ['세제','seje_H.mp3','seje_M.mp3','cleaning material'],
    ['소개','soge_H.mp3','soge_M.mp3','introduction'],
    ['수도','sudo_H.mp3','sudo_M.mp3','capital city'],
    ['시다','sida_H.mp3','sida_M.mp3','to be sour'],
    ['아내','ane_H.mp3','ane_M.mp3','wife'],
    ['아래','arae_H.mp3','arae_M.mp3','the bottom'],
    ['아주','aju_H.mp3','aju_M.mp3','very'],
    ['아주머니','ajumeoni_H.mp3','ajumeoni_M.mp3','middle age woman'],
    ['애기','aegi_H.mp3','aegi_M.mp3','baby'],
    ['어디','eodi_H.mp3','eodi_M.mp3','where'],
    ['어리다','eorida_H.mp3','eorida_M.mp3','to be very young'],
    ['오래','orae_H.mp3','orae_M.mp3','for a long time'],
    ['오리','ori_H.mp3','ori_M.mp3','duck'],
    ['우리','uri_H.mp3','uri_M.mp3','we'],
    ['우주','uju_H.mp3','uju_M.mp3','universe'],
    ['이사','isa_H.mp3','isa_M.mp3','moving (house)'],
    ['이자','ija_H.mp3','ija_M.mp3','interest (money)'],
    ['자기','jagi_H.mp3','jagi_M.mp3','honey, darling or oneself '],
    ['자주','jaju_H.mp3','jaju_M.mp3','often'],
    ['주머니','jumeoni_H.mp3','jumeoni_M.mp3','pocket'],
    ['주소','juso_H.mp3','juso_M.mp3','address'],
    ['주스','Juice_H.mp3','Juice_M.mp3','juice'],
    ['조개','joge_H.mp3','joge_M.mp3','shellfish'],
    ['저자','jeoja_H.mp3','jeoja_M.mp3','author'],
    ['제주도','jejudo_H.mp3','jejudo_M.mp3','Jeju, an island in Korea'],
    ['지다','jida_H.mp3','jida_M.mp3','to lose'],
    ['지구','jigu_H.mp3','jigu_M.mp3','earth']
]}