var setOne = [
  ['가구', 'gagu_H.mp3', 'gagu_M.mp3', 'furniture'],
  ['가나다', 'ganada_H.mp3', 'ganada_M.mp3', 'korean alphabet'],
  ['가다', 'gada_H.mp3', 'gada_M.mp3', 'to go'],
  ['가두다', 'gaduda_H.mp3', 'gaduda_M.mp3', 'to lock in'],
  ['고구마', 'goguma_H.mp3', 'goguma_M.mp3', 'sweet potato'],
  ['고기', 'gogi_H.mp3', 'gogi_M.mp3', 'meat'],
  ['고모', 'gomo_H.mp3', 'gomo_M.mp3', 'father\'s sister'],
  ['구두', 'gudu_H.mp3', 'gudu_M.mp3', 'dress shoes'],
  ['기도', 'gido_H.mp3', 'gido_M.mp3', 'prayer'],
  ['나가다', 'nagada_H.mp3', 'nagada_M.mp3', 'go out'],
  ['나누다', 'nanuda_H.mp3', 'nanuda_M.mp3', 'to divide'],
  ['나무', 'namu_H.mp3', 'namu_M_(1).mp3', 'tree'],
  ['나오다', 'naoda_H.mp3', 'naoda_M.mp3', 'to come out'],
  ['나이', 'nai_H.mp3', 'nai_M.mp3', 'age'],
  ['누가', 'nuga_H.mp3', 'nuga_M.mp3', 'who'],
  ['두구', 'nugu_H.mp3', 'nugu_M.mp3', 'who'],
  ['누나', 'nuna_H.mp3', 'nuna_M.mp3', 'older sister'],
  ['다가가다', 'dagagada_H.mp3', 'dagagada_M.mp3', 'approach to someone'],
  ['다니다', 'danida_H.mp3', 'danida_M.mp3', 'to go to'],
  ['도구', 'dogu_H.mp3', 'dogu_M.mp3', 'instrument, tool'],
  ['마다', 'mada_H.mp3', 'mada_M.mp3', 'every'],
  ['마디', 'madi_H.mp3', 'madi_M.mp3', 'joint, knot'],
  ['모기', 'mogi_H.mp3', 'mogi_M.mp3', 'mosquito'],
  ['아기', 'agi_H.mp3', 'agi_M.mp3', 'baby'],
  ['아마도', 'amado_H.mp3', 'amado_M.mp3', 'maybe'],
  ['아우', 'au_H.mp3', 'au_M.mp3', 'man\'s younger brother (archaic)'],
  ['아이', 'ai_H.mp3', 'ai_M.mp3', 'child'],
  ['오다', 'oda_H.mp3', 'oda_M.mp3', 'to come'],
  ['오이', 'oi_H_(1).mp3', 'oi_M.mp3', 'cucumber'],
  ['이기다', 'igida_H.mp3', 'igida_M.mp3', 'to win'],
  ['이모', 'imo_H.mp3', 'imo_M.mp3', 'mother\'s sister']
];